telemetry = false

[install]
exact = true

[test]
coverage = true
coveragePathIgnorePatterns = ["tests/**", "src/main.ts"]
coverageThreshold = { lines = 1.0, functions = 1.0, statements = 1.0 }
coverageSkipTestFiles = true
preload = ["./tests/preload.ts"]
