name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
    secrets: inherit

  test:
    uses: ./.github/workflows/tests.yml
    secrets: inherit

  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
