name: Test Suite

on:
  workflow_call:
    inputs:
      debug_enabled:
        description: 'Enable debug logging'
        required: false
        default: false
        type: boolean

env:
  BUN_VERSION: '1.2.14'

jobs:
  test:
    name: Test on ${{ matrix.os }} (Bun ${{ matrix.bun-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        bun-version: ['1.2.14', 'latest']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}
          no-cache: ${{ runner.os == 'Windows' }}  # Disable cache on Windows due to issues

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ matrix.bun-version }}-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-${{ matrix.bun-version }}-
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bun run lint
        if: matrix.os == 'ubuntu-latest' && matrix.bun-version == '1.2.14'

      - name: Run type check
        run: bun run typecheck

      - name: Run tests
        run: bun test --coverage
        env:
          LOG_EXPECTED_ERRORS: ${{ inputs.debug_enabled }}

      - name: Upload coverage reports
        if: matrix.os == 'ubuntu-latest' && matrix.bun-version == '1.2.14'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false